name: CI

on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main

jobs:
  build:
    runs-on: ubuntu-latest
    environment: quay.io

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Log in to Quay.io
      run: |
        echo "${{ secrets.QUAY_PASSWORD }}" | podman login quay.io -u "${{ secrets.QUAY_USERNAME }}" --password-stdin

    - name: Get git commit hash
      id: git_hash
      run: echo "hash=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT

    - name: Build v2 image with Podman
      working-directory: ./week3/v2
      run: |
        podman build -t quay.io/ansdudgh980/bootc:${{ steps.git_hash.outputs.hash }} -f Containerfile .

    - name: Push image to Quay.io
      run: |
        podman push quay.io/ansdudgh980/bootc:${{ steps.git_hash.outputs.hash }}
