name: CI

on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Get git commit hash
      id: git_hash
      run: echo "hash=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT

    - name: Build v2 image with Podman
      working-directory: ./week3/v2
      run: |
        podman build -t quay.io/ansdudgh980/bootc:${{ steps.git_hash.outputs.hash }} -f Containerfile .

    - name: Test v2 image
      run: |
        podman run --rm quay.io/ansdudgh980/bootc:${{ steps.git_hash.outputs.hash }} echo "v2 build successful"

    - name: Push image to Quay.io
      run: |
        podman push quay.io/ansdudgh980/bootc:${{ steps.git_hash.outputs.hash }}
